### ISSUE TITLE
Fails if empty file?

### ISSUE THREAD

**Issue by timneedham** [KenanY/first-line#8]
Hi,

Seems to never return if pointed at an empty file?

Cheers

Tim

**Comment by KenanY** [comment]
Hmm, yeah, should probably result in a blank string or `null`.

**Comment by timneedham** [comment]
Sorry... and the same behaviour if the line is empty too?

**Comment by KenanY** [comment]
Working on this now. Planning on having empty files call `callback(null, null)` (since there's no data, then the result should probably be either `null` or an empty `Buffer`).

I was thinking that files with just newlines should do `callback(null, Buffer.from(''))`, but I'm having trouble actually implementing that.

Do you have any opinions on what behavior(s) should occur for either empty files or files with just newlines?

**Comment by timneedham** [comment]
Hi,

**Thanks for looking into this, very much appreciated.**

For the empty-file case... calling `callback(null, null`)  would work great for us,
And the same for a file contaiing just new lines.

Thanks for all your help.

Tim

**Comment by KenanY** [comment]
Published fix in `1.0.3`.
